#!/usr/bin/php
<?php
/*
 * Copyright (C) 2019 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();
$action = $data['action'];

$v = new LegacyValidator($data);

switch ($action) {

case "create-host":
    $db = new EsmithDatabase('hosts');
    $v->declareParameter('name', Validate::USERNAME);
    if ($db->getKey($data['name'])) {
        $v->addValidationError('name', 'host_key_exists', $data['name']);
    }
    $v->declareParameter('IpAddress', Validate::IPv4);
    break;

case "update-host":
    $db = new EsmithDatabase('hosts');
    if (!$db->getKey($data['name'])) {
        $v->addValidationError('name', 'non_existing_host', $data['name']);
    }
    $v->declareParameter('IpAddress', Validate::IPv4);
    break;

case "delete-host":
    $deleteValidator = $v->createValidator()->platform('fwobject-host-delete', 'hosts');
    if( ! $deleteValidator->evaluate($data['name'])) {
        $v->addValidationError('name', 'not_removable');
    }
    break;

}

# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}

