#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for nethserver-firewall-base-update event
#--------------------------------------------------

$event = "nethserver-firewall-base-update";

event_templates($event, 
                '/etc/shorewall/shorewall.conf',
                '/etc/shorewall/interfaces',
                '/etc/shorewall/masq',
                '/etc/shorewall/policy',
                '/etc/shorewall/rules',
                '/etc/shorewall/zones',
                '/etc/shorewall/providers',
                '/etc/shorewall/rtrules',
                '/etc/shorewall/tcrules',
                '/etc/shorewall/tunnels',
                '/etc/shorewall/hosts',
                '/etc/shorewall/findgw',
                '/etc/sudoers');

event_templates($event, '/etc/lsm/lsm.conf');

event_actions($event,
              'initialize-default-databases' => '00',
              'nethserver-shorewall-conf' => '02',
              'nethserver-firewall-base-conf' => '03');

event_services($event,
                     'rsyslog' => 'restart', 
                     'shorewall' => 'restart',
                     'lsm' => 'restart' );


#--------------------------------------------------
# actions for nethserver-firewall-base-save event
#--------------------------------------------------

$event = "nethserver-firewall-base-save";

event_templates($event, 
                '/etc/shorewall/shorewall.conf',
                '/etc/shorewall/interfaces',
                '/etc/shorewall/masq',
                '/etc/shorewall/policy',
                '/etc/shorewall/rules',
                '/etc/shorewall/tcinterfaces',
                '/etc/shorewall/tcpri',
                '/etc/shorewall/providers',
                '/etc/shorewall/rtrules',
                '/etc/shorewall/tcrules',
                '/etc/shorewall/tunnels',
                '/etc/shorewall/hosts',
                '/etc/shorewall/zones');

event_templates($event, '/etc/lsm/lsm.conf');

event_services($event, 
                     'shorewall' => 'restart',
                     'lsm' => 'restart' );


#--------------------------------------------------
# actions for firewall-objects-modify event
#--------------------------------------------------

$event = "firewall-objects-modify";

event_actions($event,
              'nethserver-firewall-base-save' => '90'
);

#--------------------------------------------------
# actions for wan-uplink-update event
#--------------------------------------------------

$event = "wan-uplink-update";

event_actions($event,
              'nethserver-shorewall-wan-update' => '50'
);

#--------------------------------------------------
# actions for static-routes-save event
#--------------------------------------------------

$event = "static-routes-save";

event_actions($event,
              'providers-static-routes' => '20'
);

#--------------------------------------------------
# actions for firewall-object-exists validator
#--------------------------------------------------

validator_actions('firewall-object-exists', qw(
                  uniq-fwobject 20
));

validator_actions($_, qw(
                  fwobject-referenced 20
)) foreach (qw(
   fwobject-host-group-delete
   fwobject-host-delete
   fwobject-zone-delete
   fwobject-fwservice-delete
));



