#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for nethserver-firewall-base-update event
#--------------------------------------------------

$event = "nethserver-firewall-base-update";

event_templates($event, 
                '/etc/shorewall/shorewall.conf',
                '/etc/shorewall/interfaces',
                '/etc/shorewall/masq',
                '/etc/shorewall/policy',
                '/etc/shorewall/rules',
                '/etc/shorewall/zones',
                '/etc/shorewall/providers',
                '/etc/shorewall/rtrules',
                '/etc/shorewall/tcrules',
                '/etc/shorewall/tunnels',
                '/etc/shorewall/hosts',
                '/etc/sudoers');

event_templates($event, '/etc/lsm/lsm.conf');

event_actions($event,
              'initialize-default-databases' => '00',
              'nethserver-firewall-base-conf' => '02');

event_services($event, 
                     'shorewall' => 'restart',
                     'lsm' => 'restart' );


#--------------------------------------------------
# actions for nethserver-firewall-base-save event
#--------------------------------------------------

$event = "nethserver-firewall-base-save";

event_templates($event, 
                '/etc/shorewall/shorewall.conf',
                '/etc/shorewall/interfaces',
                '/etc/shorewall/masq',
                '/etc/shorewall/policy',
                '/etc/shorewall/rules',
                '/etc/shorewall/tcinterfaces',
                '/etc/shorewall/tcpri',
                '/etc/shorewall/providers',
                '/etc/shorewall/rtrules',
                '/etc/shorewall/tcrules',
                '/etc/shorewall/tunnels',
                '/etc/shorewall/hosts',
                '/etc/shorewall/zones');

event_templates($event, '/etc/lsm/lsm.conf');

event_services($event, 
                     'shorewall' => 'restart',
                     'lsm' => 'restart' );


#--------------------------------------------------
# actions for interface-update event
#--------------------------------------------------

$event = "interface-update";

event_templates($event,
                '/etc/shorewall/interfaces',
                '/etc/shorewall/masq',
                '/etc/shorewall/providers',
                );

event_services($event, 'shorewall' => 'restart');

