#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use NethServer::Firewall;

my $a = shift;
my $b = shift;

exit 0 if ($a eq $b);

my $fw = new NethServer::Firewall();

my $a_addr = $fw->getAddress($a, 1);
my $b_addr = $fw->getAddress($b, 1);

exit 1 if (!$a_addr || !$b_addr);

(my $a_zone, $a_addr) = split(":", $fw->getZone($a_addr));
(my $b_zone, $b_addr) = split(":", $fw->getZone($b_addr));

exit 0 if ($a_zone eq $b_zone);

exit 1;
