#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/nethserver-firewall-base/lib/firewall_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

case $action in
    create)
       new_name=$(expr $(/sbin/e-smith/db portforward showjson | jq -r '[.[].name] | max') + 1)
       src=$(echo $data | jq -rc '.Src | map(tostring) | join(",")')
       proto=$(_get Proto)
       if [ "$proto" == "tcpudp" ]; then
           proto="tcp,udp"
       fi

       /sbin/e-smith/db portforward set "$new_name"  pf Allow "$(_get Allow)" \
           Description "$(_get Description)" Dst "$(_get Dst)" \
           DstHost "$(_get DstHost)" Log "$(_get Log)" \
           OriDst "$(_get OriDst)" Proto "$proto" \
           Src "$src" status "$(_get status)"

        ;;

   update)
       src=$(echo $data | jq -rc '.Src | map(tostring) | join(",")')
       proto=$(_get Proto)
       if [ "$proto" == "tcpudp" ]; then
           proto="tcp,udp"
       fi

       /sbin/e-smith/db portforward setprop "$(_get name)"  Allow "$(_get Allow)" \
           Description "$(_get Description)" Dst "$(_get Dst)" \
           DstHost "$(_get DstHost)" Log "$(_get Log)" \
           OriDst "$(_get OriDst)" Proto "$proto" \
           Src "$src" status "$(_get status)"
       ;;

   delete)
       /sbin/e-smith/db portforward delete "$(_get name)"
       ;;

    *)
        error
        ;;
esac

if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
fi

/sbin/e-smith/signal-event -j firewall-adjust

if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
