#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/nethserver-firewall-base/lib/firewall_functions


case $action in

    "update-rule")
        fw_rule "update"
        ;;

    "reorder")
        save_db fwrules
        echo $data | /usr/libexec/nethserver/api/nethserver-firewall-base/lib/rules-reorder
        ;;
    "update-separator")
        fw_separator "update"
        ;;
    "create-separator")
        fw_separator "create"
        ;;
    "delete-separator")
        delete_separator
        ;;
    *)
        error
        ;;
esac
