#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/nethserver-firewall-base/lib/firewall_functions


case $action in
    "update-rule")
        fw_rule "update"
        ;;

    "provider")
        save_db networks
        # retrieve provider for the given interface
        provider=$(/sbin/e-smith/db networks showjson | jq -r '.[] | select((.type == "provider") and (.props.interface == "'$(_get name)'")) | .name')
        /sbin/e-smith/db networks setprop $provider weight "$(_get weight)"
        /sbin/e-smith/db networks setprop "$(_get name)"  FwOutBandwidth "$(_get FwOutBandwidth)" FwInBandwidth  "$(_get FwInBandwidth)" nslabel  "$(_get nslabel)"
        ;;

    "provider-enable")
        save_db networks
        /usr/sbin/shorewall enable "$(_get name)"
        ;;

    "provider-disable")
        save_db networks
        /usr/sbin/shorewall disable "$(_get name)"
        ;;

    "wan")
        notifywanfrom=$(/sbin/e-smith/db configuration getprop root SenderAddress)
        notifyto=$(/sbin/e-smith/db configuration getprop root EmailAddress)
        save_db configuration
        /sbin/e-smith/db configuration setprop firewall WanMode "$(_get WanMode)" NotifyWan "$(_get NotifyWan)" \
            MaxNumberPacketLoss "$(_get MaxNumberPacketLoss)" MaxPercentPacketLoss "$(_get MaxPercentPacketLoss)" PingInterval "$(_get PingInterval)" \
            CheckIP "$(_get_array CheckIP)" NotifyWanTo "$notifyto" NotifyWanFrom "$notifywanfrom"
        ;;
esac

if [ $? -gt 0 ]; then
    error "SaveFailed" "check_logs"
else
    success
fi

