#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/nethserver-firewall-base/lib/firewall_functions

case $action in

    "settings")
        save_db configuration
        /sbin/e-smith/db configuration setprop firewall ExternalPing "$(_get ExternalPing)" Policy "$(_get Policy)" HairpinNat "$(_get HairpinNat)" \
            MACValidationPolicy "$(_get MACValidationPolicy)" MACValidation "$(_get MACValidation)" VpnPolicy "$(_get VpnPolicy)" SipAlg "$(_get SipAlg)"
        /sbin/e-smith/signal-event -j firewall-adjust
        /sbin/e-smith/signal-event -j conntrack-adjust
        ;;
    "apply")
        apply_config
        ;;
    "reset")
        reset_config
        ;;
    "restore")
        restore_config
        ;;
    "discard")
        discard_backup
        ;;
    *)
        error
        ;;
esac

if [ $? -gt 0 ]; then
    error "EventFailed" "check_logs"
else
    success
fi
