#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Disable ethernet offloading on interfaces where traffic shaping is enabled
#

use esmith::NetworksDB;
use strict;

my $ndb = esmith::NetworksDB->open_ro() || die("Could not open networks DB");

foreach my $red ($ndb->red()) {
    my $interface = $red->key;
    my $in = $red->prop('FwInBandwidth') || next;
    my $out = $red->prop('FwOutBandwidth') || next;
    foreach my $opt (qw(tso gso gro)) {
       my $cmd = "ethtool -K ".$red->key." $opt off\n";
       system($cmd);
    }
}

exit 0;
