#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::NetworksDB;

my $ndb = esmith::NetworksDB->open() || die('Could not open NetworksDB');
my $errors = 0;

# If an interface becomes part of a logical interface its firewall zone
# records are transferred to the logical interface
foreach my $zone ($ndb->zones()) {
    my $interface = $ndb->get($zone->prop('Interface'));
    if(! $interface || !$interface->prop('role')) {
        warn(sprintf("[ERROR] zone %s has a dangling Interface reference\n", $zone->key));
        $errors ++;
    }
    if($interface->prop('role') eq 'bridged') {
        $zone->set_prop('Interface', $interface->prop('bridge'));
    } elsif($interface->prop('role') eq 'slave') {
        $zone->set_prop('Interface', $interface->prop('master'));
    }
}

# When a logical interface is removed, its successor inherits any reference
# through the "interface-rename" action

if($errors > 0) {
    exit(1);
}
