#!/usr/bin/perl -w
#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

# 
# This script will find a suitable checkip for all providers and create static routes if needed.
# 

use esmith::NetworksDB;

my $ndb = esmith::NetworksDB->open();
my $rdb = esmith::ConfigDB->open('routes');

# Cleanup old routes
foreach my $r ($rdb->get_all_by_prop('type' => 'provider-static')) {
    $r->delete();
}

foreach my $p ($ndb->get_all_by_prop('type' => 'provider')) {
    my $interface = $p->prop('interface') || '';
    next if ($interface eq '');
    my $checkip = $p->prop('checkip') || '';
    my $red = $ndb->get($interface);
    my $gateway = $red->prop('gateway') || '';
    if ($gateway eq '') { # find gateway from dhcp lease
        $gateway = `/bin/bash /etc/shorewall/findgw $interface 2>/dev/null`;
    }
    my $set_routes = 1;

    if ($checkip eq '') {
        # find next hop
        $checkip = `/bin/ping -c 1 -I $interface -t 2 8.8.8.8 | /bin/grep 'Time to live'  | /bin/cut -d' ' -f2`;
        $checkip =~ s/\s//g;
        if ($checkip) {
            $ndb->set_prop($p->key, 'checkip', $checkip);
        } else { # fallback: set checkip to red interface gateway
            $ndb->set_prop($p->key, 'checkip', $gateway);
            # no routes needed
            $set_routes = 0;
        }
    }

    if ($set_routes) {
        $rdb->set_prop($checkip, 'Mask', '255.255.255.255', type => 'provider-static');
        $rdb->set_prop($checkip, 'Router', $gateway);
        $rdb->set_prop($checkip, 'Description', 'Provider: '.$p->key.' - DO NOT REMOVE');
    }

}
