#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package NethServer::Firewall;

use strict;
use esmith::ConfigDB;
use esmith::NetworksDB;
use NethServer::Firewall;
use File::Basename;
my $ndb = esmith::NetworksDB->open();
my $cdb = esmith::ConfigDB->open();
my $fw = new NethServer::Firewall();
my %reds;

foreach ($ndb->red()) {
    $reds{$_->key} = '';
}

# Delete providers associated to non-existing red interfaces
foreach my $provider ( $ndb->get_all_by_prop('type' => 'provider') ) {
    my $i = $provider->prop('interface') || '';
    if ($i eq '' || !exists($reds{$i})) {
        $provider->delete();
    }
}

my @providers = $fw->getProviders();

if (scalar(@providers) >= 2) {
    $cdb->set_prop('lsm','status','enabled');
} else {
    $cdb->set_prop('lsm','status','disabled');
}

# Delete shorewall status for non-existing interfaces
my @status_files = glob('/var/lib/shorewall/*.status');
foreach (@status_files) {
    my $interface = basename($_,('.status'));
    my $i = $ndb->get($interface) || undef;
    my $role = $ndb->get_prop($interface, 'role') || '';
    if (!defined($i) || $role ne 'red') {
        print "[INFO] Removing status file '$_'\n";
        unlink($_);;
    }
}
