#!/usr/bin/perl

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

use strict;

use esmith::HostsDB;

my $dbName = shift || die("Missing DB argument");
my $hostKey = shift || die("Missing host key argument");

my $hdb = esmith::HostsDB->open();

my @groups = ();
my @members = ();

foreach my $record ($hdb->get_all_by_prop('type' => 'host-group')) {
    @members = split ',', $record->prop('Members');
    if (grep(/^$hostKey$/, @members)) {
	push @groups, $record->key;
    }
}

if(@groups) {
    print join(', ', @groups) . "\n";
    exit(3);
}

exit(0);
