#!/usr/bin/perl

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#


use JSON;
use NethServer::Firewall;
use esmith::NetworksDB;
use esmith::ConfigDB;

my $action = shift;
my $rule = shift || die('Missing account rule argument');

my $fwRulesDb = esmith::ConfigDB->open_ro('fwrules');
my $fw = new NethServer::Firewall();

my $props = JSON->new->utf8->decode($rule);

if($props->{'ServiceRaw'} !~ /^ndpi;/) {
    # ignore non-ndpi actions
    exit(0);
}

if($props->{'SrcRaw'} eq 'any' || $props->{'DstRaw'} eq 'any') {
    print "The 'any' target cannot be set as Source or Destination.\n";
    exit(3);
}

if($props->{'SrcRaw'} eq 'fw' || $props->{'DstRaw'} eq 'fw') {
    print "The firewall cannot be set as Source or Destination.\n";
    exit(4);
}

if($props->{'Action'} =~ m/^provider;/) {
    print "DPI protocol is not allowed with route rules.\n";
    exit(5);
}

if($props->{'Action'} =~ m/^reject/) {
    print "Reject action is not supported for NDPI.\n";
    exit(6);
}
