#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;

my $dbName = shift;
my $key = shift;

if($dbName ne 'networks') {
    die("[ERROR] Unexpected DB argument: $dbName");
}

foreach(esmith::ConfigDB->open_ro()->get_all_by_prop('type' => 'service')) {
    if(grep { $_ eq $key } split(/,/, $_->prop('access'))) {
        exit(3);
    }
}

exit(0);