#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use NethServer::Firewall;
use esmith::NetworksDB;

my $objName = shift || die('Missing account object argument');
my $fw = new NethServer::Firewall();
my $val = undef;

my @tmp = split(/;/,$objName);
if ($tmp[0] eq "zone") {
    my $ndb = esmith::NetworksDB->open_ro();
    $val = $ndb->get($tmp[1]);
} else {
    $val = $fw->getAddress($objName);
}

if ($val)
{
    exit 0;
} else {
    print "The firewall object '$objName' does not exists\n";
    exit 3;
}
