#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/nethserver-firewall-base/lib/firewall_functions


case $action in
    "update-rule")
        fw_rule "update"
        ;;

    "update-class")
        bindto=$(echo $data | jq -rc '.BindTo | map(tostring) | join(",")')
        save_db tc
        /sbin/e-smith/db tc set "$(_get name)" class MinOutputRate "$(_get MinOutputRate)" MaxOutputRate "$(_get MaxOutputRate)" MaxInputRate "$(_get MaxInputRate)" MinInputRate "$(_get MinInputRate)" \
            Description "$(_get Description)" Unit "$(_get Unit)" BindTo "$bindto"
        ;;

    "reorder")
        save_db fwrules
        echo $data | /usr/libexec/nethserver/api/nethserver-firewall-base/lib/rules-reorder
        ;;
esac

if [ $? -gt 0 ]; then
    error "SaveFailed" "check_logs"
else
    success
fi

